# Generated by Django 5.1 on 2024-09-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='post',
        ),
        migrations.RemoveField(
            model_name='supportrequests',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room_Post', to='API.rooms'),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='amenities',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(choices=[('WATER', 'Nuoc'), ('ELECTRICITY', 'Dien'), ('INTERNET', 'Internet'), ('OTHER', 'Khac')], default='OTHER', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='API.rooms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='Room_Amenities', to='API.amenities'),
        ),
    ]
