# Generated by Django 5.1 on 2024-09-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_amenities_remove_rooms_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='other_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
