# Generated by Django 5.1 on 2024-09-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rooms_other_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='other_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
