# Generated by Django 5.1 on 2024-09-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_rooms_other_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
