# Generated by Django 5.1 on 2024-09-03 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
