# Generated by Django 5.1 on 2024-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_user_gender_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nu'), ('OTHER', 'Khac')], default='MALE', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('LANDLORD', 'landlord'), ('WEBMASTER', 'webmaster')], default='CUSTOMER', max_length=30),
        ),
    ]
