# Generated by Django 5.1 on 2024-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='quanlity',
            field=models.IntegerField(default=1),
        ),
    ]
