# Generated by Django 5.1 on 2024-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_amenities_quanlity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
