# Generated by Django 5.1 on 2024-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_rooms_latitude_alter_rooms_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
