# Generated by Django 5.1 on 2024-09-28 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_post_is_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Landlord_Reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='reviews_landlord',
            field=models.ManyToManyField(blank=True, related_name='reviewed_users', to='API.reviews'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='selected_criteria',
            field=models.ManyToManyField(blank=True, related_name='Selected_Reviews', to='API.reviewcriterion'),
        ),
    ]
