# Generated by Django 5.1 on 2024-09-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_reviewcriterion_remove_reviews_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
