# Generated by Django 5.1 on 2024-10-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_reviews_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('customer', 'landlord'), name='unique_customer_landlord_review'),
        ),
    ]
