# Generated by Django 5.0.3 on 2025-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('POST_APPROVED', 'Bài đăng được duyệt'), ('NEW_REVIEW', 'Đánh giá mới'), ('NEW_FOLLOWER', 'Người theo dõi mới'), ('NEW_MESSAGE', 'Tin nhắn mới')], max_length=50),
        ),
    ]
