# Generated by Django 5.0.3 on 2025-04-07 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_vector', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='max_area',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='max_price',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='min_area',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='min_price',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-last_searched'], name='API_searchh_user_id_a1255b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['room_type', 'city'], name='API_searchh_room_ty_9aa32d_idx'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
