# Generated by Django 5.0.3 on 2025-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_userpreference_alter_searchhistory_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='vector_size',
            field=models.IntegerField(default=0),
        ),
    ]
