# Generated by Django 5.0.3 on 2025-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_userpreference_vector_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
