# Generated by Django 5.0.3 on 2025-04-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_searchhistory_day_of_week_searchhistory_search_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_time',
        ),
    ]
