# Generated by Django 5.0.3 on 2025-05-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_posttype_payment_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='post_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.posttype'),
        ),
    ]
