# Generated by Django 5.0.3 on 2025-05-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_alter_payment_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('LANDLORD', 'landlord'), ('WEBMASTER', 'webmaster')], default='LANDLORD', max_length=30),
        ),
    ]
