# Generated by Django 5.0.3 on 2025-05-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('LANDLORD', 'landlord'), ('WEBMASTER', 'webmaster')], default='CUSTOMER', max_length=30),
        ),
    ]
