# Generated by Django 5.0.3 on 2025-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
